### ISSUE TITLE
Processes not handled properly if ps command not present

### ISSUE THREAD

**Issue by rubiesonthesky** [photostructure/batch-cluster.js#13]
This concers `exiftool-vendored` usage but the problem is coming from this library.

When using `exiftool-vendored` in minimized Docker image, for example, Debian slim, processed are not killed / terminated correctly because `ps` command is not found. `procps` is not by default installed on slim version.

1. Is there any way to add support for systems that do not have access to `ps` command? Propably unlikely.
1. Could there be some warning printed or debug command to check if `ps` is missing?
1. Could this requirement be documented clearly here and other libraries that are using this library, namely exiftool-vendored?

I'm sure I will not be only one having this issue where processes are just spawned with every task invocation and then reported "dead" because this library can't get their pid. Using minimized / slim Docker images is the recommendation and you wouldn't think that using node library is depending having `ps` command available :) After adding procps to my Docker image, things are working as they should be / same manner as my local dev environment.

**Comment by mceachen** [comment]
Interesting: I've always run this [in a docker container that had installed `procps`](https://github.com/photostructure/photostructure-for-servers). TBH, I'd never even considered `ps` not being available on a POSIX system!

I'll put a warning on this package and exiftool-vendored for now. If you want to take a stab at a PR, I'd be happy to review it.
